# import json

import pytest

from app.services.evaluations_crawler import EvaluationCrawler
from app.utils.browser import BrowserManager

EVALUATION_DETAIL_URLS = [
    "https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2025002494&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=001&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=0&NAME=&JGY_CD=1310900006&HYK_YR=2024&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=21&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13109&H_NAME=&J_NAME=&SVCDBR_CD=21&STEP_SVCSBRCD=001&STEP_SVCSBRCD=013",
    "https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2021003561&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=344&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=0&NAME=&JGY_CD=1320500489&HYK_YR=2021&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=23&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13205&H_NAME=&J_NAME=&SVCDBR_CD=23&STEP_SVCSBRCD=344&STEP_SVCSBRCD=342",
    "https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2022002398&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=001&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=0&NAME=&JGY_CD=1311800350&HYK_YR=2021&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=21&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13118&H_NAME=&J_NAME=&SVCDBR_CD=21&STEP_SVCSBRCD=001&STEP_SVCSBRCD=013",
    "https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2022003626&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=344&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=80&NAME=&JGY_CD=1320101419&HYK_YR=2022&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=23&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=false&COLOR_HYK_ID=2026000227&BEFORE_FLG=false&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13201&H_NAME=&J_NAME=&SVCDBR_CD=23&STEP_SVCSBRCD=344&STEP_SVCSBRCD=342",
    "https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2023003193&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCDBRCD=&PTN_CD=&SVCSBRCDALL=&SVCSBRCD=113&AREA1=&AREA2=&AREA3=&HYK_YR=&SCHHYK_YR=&NAME=&JGY_CD=1320100515&MODE=multi&DVS_CD=&SVCDBR_CD=25&SVCSBR_CD=&ROW=0&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13201&H_NAME=&J_NAME=&SVCDBR_CD=25&STEP_SVCSBRCD=113",
]


@pytest.mark.asyncio
async def test_evaluations_crawler_extraction():
    async with BrowserManager(headless=True) as browser_context:
        page = await browser_context.new_page()
        crawler = EvaluationCrawler.__new__(EvaluationCrawler)

        records = []
        for url in EVALUATION_DETAIL_URLS:
            await page.goto(url)

            record = await crawler._extract_evaluation_data(page)
            records.append(record)

            # add -s flag to command to print the record
            # print(json.dumps(record, ensure_ascii=False, indent=2))

        # https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2025002494&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=001&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=0&NAME=&JGY_CD=1310900006&HYK_YR=2024&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=21&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13109&H_NAME=&J_NAME=&SVCDBR_CD=21&STEP_SVCSBRCD=001&STEP_SVCSBRCD=013
        assert records[0]["depot_name"] == "成幸ホーム"
        assert records[0]["evaluation_agency_name"] == "公益社団法人　長寿社会文化協会"
        assert records[0]["evaluation_year"] == 2024
        assert records[0]["evaluation_date"] == "2024-09-10"
        assert records[0]["evaluation_end_date"] == ""  # No value

        # https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2021003561&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=344&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=0&NAME=&JGY_CD=1320500489&HYK_YR=2021&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=23&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13205&H_NAME=&J_NAME=&SVCDBR_CD=23&STEP_SVCSBRCD=344&STEP_SVCSBRCD=342
        assert (
            records[1]["depot_name"] == "なないろ／なないろ"
        )  # (なないろ／なないろ \xa0\xa0他1ユニット\xa0\xa0\xa0\xa0他ユニットを表示) Remove unit info & button
        assert records[1]["evaluation_agency_name"] == "合同会社　フェアリンク"
        assert records[1]["evaluation_year"] == 2021
        assert records[1]["evaluation_date"] == "2021-10-01"
        assert (
            records[1]["evaluation_end_date"] == "2012-11-29"
        )  # (should be 2021-11-29) Assumed to be a typo

        # https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2022002398&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=001&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=0&NAME=&JGY_CD=1311800350&HYK_YR=2021&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=21&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13118&H_NAME=&J_NAME=&SVCDBR_CD=21&STEP_SVCSBRCD=001&STEP_SVCSBRCD=013
        assert records[2]["depot_name"] == "特別養護老人ホームさくら館"
        assert records[2]["evaluation_agency_name"] == "株式会社　学研Ａｄｖａｎｃｅ"
        assert records[2]["evaluation_year"] == 2021
        assert records[2]["evaluation_date"] == "2021-06-28"
        assert (
            records[2]["evaluation_end_date"] == "3022-03-17"
        )  # (should be 2022-03-17) Assumed to be a typo

        # https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2022003626&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCSBRCD=344&SVCDBRCD=&AREA1=&AREA2=&AREA3=&ROW=80&NAME=&JGY_CD=1320101419&HYK_YR=2022&SCHHYK_YR=&MODE=multi&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&DVS_CD=&SVCDBR_CD=23&SVCSBR_CD=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&SVCSBRCDALL=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=false&COLOR_HYK_ID=2026000227&BEFORE_FLG=false&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13201&H_NAME=&J_NAME=&SVCDBR_CD=23&STEP_SVCSBRCD=344&STEP_SVCSBRCD=342
        assert (
            records[3]["depot_name"] == "ＰＡＬＬＥＴ／ＰＡＬＬＥＴ１"
        )  # (ＰＡＬＬＥＴ／ＰＡＬＬＥＴ１ \xa0\xa0他3ユニット\xa0\xa0\xa0\xa0他ユニットを表示) Remove unit info & button
        assert (
            records[3]["evaluation_agency_name"]
            == "特定非営利活動法人　医療・介護情報ネットワーク"
        )
        assert records[3]["evaluation_year"] == 2022
        assert records[3]["evaluation_date"] == "2022-09-04"
        assert records[3]["evaluation_end_date"] == "2022-10-31"

        # https://www.fukunavi.or.jp/fukunavi/controller?actionID=hyk&cmd=hyklstdtldigest&BEF_PRC=hyk&HYK_ID=2023003193&HYK_ID1=&HYK_ID2=&HYK_ID3=&HYK_ID4=&HYK_ID5=&JGY_CD1=&JGY_CD2=&JGY_CD3=&JGY_CD4=&JGY_CD5=&SCHSVCSBRCD=&SVCDBRCD=&PTN_CD=&SVCSBRCDALL=&SVCSBRCD=113&AREA1=&AREA2=&AREA3=&HYK_YR=&SCHHYK_YR=&NAME=&JGY_CD=1320100515&MODE=multi&DVS_CD=&SVCDBR_CD=25&SVCSBR_CD=&ROW=0&FROMDT=&SCH_ACTION=hyklst&KOHYO=&GEN=&HYKNEN=&LISTSVC=&ORDER=&HYK_DTL_CHK=&PRMCMT_CHK=&HYK_CHK=&JGY_CHK=&SVC_CHK=&DIG_MOVE_FLG=&MLT_SVCSBR_CD1=&MLT_SVCSBR_CD2=&MLT_SVCSBR_CD3=&MLT_SVCSBR_CD4=&MLT_SVCSBR_CD5=&MLT_SVCSBR_CD6=&MLT_SVCSBR_CD7=&MLT_SVCSBR_CD8=&COLOR_FLG=&COLOR_HYK_ID=&BEFORE_FLG=&MLT_DTL_SVCSBR_CD1=&MLT_DTL_SVCSBR_CD2=&MLT_DTL_SVCSBR_CD3=&MLT_DTL_SVCSBR_CD4=&MLT_DTL_SVCSBR_CD5=&MLT_DTL_SVCSBR_CD6=&MLT_DTL_SVCSBR_CD7=&MLT_DTL_SVCSBR_CD8=&HIKAKU_SVCSBRCD=&TELOPN001_NO1=&TELOPN001_NO2=&TELOPN001_NO3=&TELOPN002_NO1=&TELOPN002_NO2=&TELOPN002_NO3=&TELOPN003_NO1=&TELOPN003_NO2=&TELOPN003_NO3=&S_MODE=service&MLT_AREA=13201&H_NAME=&J_NAME=&SVCDBR_CD=25&STEP_SVCSBRCD=113
        assert records[4]["depot_name"] == "光華"
        assert records[4]["evaluation_agency_name"] == "株式会社　福祉規格総合研究所"
        assert records[4]["evaluation_year"] == 2022
        assert records[4]["evaluation_date"] == "2022-10-20"
        assert records[4]["evaluation_end_date"] == "2023-03-31"
